export interface IDataPreview {
  beforeBacLuong: string;
  beforeHeSoBacLuong: string;
  beforeNgayHuongLuongTuNgay: string;
  beforeTotalBacLuong: string;
  birthdate: string;
  chucDanhCode: string;
  chucDanhText: string;
  currentBacLuong: string;
  currentHeSoBacLuong: string;
  currentNgayHuongLuongDenNgay: string;
  currentTotalBacLuong: string;
  donViCongTacText: string;
  fullName: string;
  hieuLucTuNgay: string;
  lcPhongBanMoiText: string;
  ngayKyToTrinh: string;
  ngayKyToTrinhDetail: string;
  ngayQuyetDinh: string;
  ngayQuyetDinhNam: string;
  ngayQuyetDinhNgay: string;
  ngayQuyetDinhThang: string;
  nguoiQuyetDinhText: string;
  phongBanText: string;
  soQuyetDinh: string;
  nguoiDaiDienCtyKyText: string;
  quocTichText: string;
  nguoiDaiDienCtyChucDanhText: string;
  daiDienQuocTich: string;
  noiSinh: string;
  trinhDoChuyenMon: string;
  hoKhauThuongTru: string;
  soCMNDOrCCCD: string;
  ngayCapCMNDOrCCCD: string;
  noiCapCMNDOrCCCD: string;
  ngayKy: string;
  loaiHopDong: string;
  ngayCoHieuLuc: string;
  ngayHetHan: string;
  heSoLuong: string;
  maNgach: string;
  luongCoBan: string;
  donViKyHopDongText: string;
  soHopDong: string;
  ngayKyHopDong: string;
  gender: {
    code: number | string;
    name: string;
  };
  phone: string;
  tkNganHang: string;
  chiNhanh: string;
  chuyenNganhDaoTao: string;
  trinhDoNgoaiNguCaoNhat: string;
  trinhDoTinHocCaoNhat: string;
  tenChungChi: string;
  thoiHanHopDong: string;
  namDaoTao: string;
  email: string;
  soPhuLuc: string;
  tenHopDong: string;
  ngayKyPhuLuc: string;
  ngayCoHieuLucPhuLuc: string;
  ngayQuyetDinhText: string;
  soSoBHXH: string;
  ngayHieuLuc: string;
  nganHangText: string;
  ngayChinhThuc: string;
  lyDoThoiViec: string;
  chucVuText?: string;
  chucVuMoiText?: string;
  phongBanMoiText?: string;
}

export interface ITemplateExportWord {
  type?: number | string;
  name: string;
  componentPreview: (dataPreview: IDataPreview) => JSX.Element;
}
